### ISSUE TITLE
change the project name

### ISSUE THREAD

**Issue by Ljzn** [rialix/rialix_core#3]
The name `rialix_core` seems too long, I think a shorter name will be better.

Maybe `rialix`, `rilix` or other.

Any advise? @jackalcooper

**Comment by Ljzn** [comment]
`ringx` `rinx` `remix`

**Comment by Ljzn** [comment]
`ray`, `rely`, `reel`, `rash`, `relief`,

**Comment by jackalcooper** [comment]
`relief` is a taken name on hex pm

**Comment by jackalcooper** [comment]
What about `nucleus` (about `core`) or `flower` (about the hash ring concept)? Neither of them are taken on hex pm.

**Comment by jackalcooper** [comment]
I'm more inclined to `flower`

**Comment by Ljzn** [comment]
After considering for a while, I wanna choose **rill** as the project name.

- **rill** means "little stream", meaning the ring among the vnode, and the strong consistance.
- start with `r`, because this project heavly based on `riak_core`, just like `elixir` with `erlang`.
- it is short, eazy to spell, type, and remember
- didn't be taken on hex.pm

what do you think about? @jackalcooper

**Comment by jackalcooper** [comment]
There is a js framework called `rill` already. [rill](https://github.com/rill-js/rill)

**Comment by jackalcooper** [comment]
The most ideal should be a word about ring and starts with r

**Comment by Ljzn** [comment]
> There is a js framework called rill already. (rill)[https://github.com/rill-js/rill]

Yes, but is ok.

**Comment by jackalcooper** [comment]
OK, that's it. Just rename it to `rill` and take the name on hex

**Comment by Ljzn** [comment]
Renamed. 

But I didn't publish a package on hex. Could you do that at any time? @jackalcooper 
Or maybe we should wait until the first release.
